### ISSUE TITLE
What is the best model released ?

### ISSUE THREAD

**Issue by yjhong89** [simon20010923/DDAMFN#11]
Hi! Thanks for sharing great work!

I want to use feature of emotion recognizer but there are many checkpoints in here.
- https://github.com/simon20010923/DDAMFN/tree/main/DDAMFN%2B%2B/checkpoints_ver2.0
- What model you recommend ?? (Maybe affectnet-8 trained model ?)

And README said that checkpoints is not your best.
- So is there any other best checkpoint available ??
![image](https://github.com/simon20010923/DDAMFN/assets/26890721/c8c50159-c064-4860-83e5-2a86ea061934)

Thanks!

**Comment by simon20010923** [comment]
I think you can try affectnet-8.

**Comment by simon20010923** [comment]
We don't have access to our best model now, but the models posted are near to the best.

**Comment by yjhong89** [comment]
Thank you!
