### ISSUE TITLE
Can you share your model DDAM_msceleb.pt

### ISSUE THREAD

**Issue by Lakphy** [simon20010923/DDAMFN#2]
The file in your code called:
```
/data/2021/code/fer/paper_2021/DAN-main/DAN-main_new/DDAM_main/pretrained/DDAM_msceleb.pt
```
It's important for us to use and learn your code, can you share the DDAM_msceleb.pt file?

**Comment by simon20010923** [comment]
The code is updated and the pretrained model is available.

**Comment by simon20010923** [comment]
Our new version DDAMFN++ is available in the folder https://github.com/simon20010923/DDAMFN/DDAMFN++, which includes new alignment code refer to https://github.com/biubug6/Pytorch_Retinaface and optimized by SAM ([Sharpness aware minimization for efficiently improving generalization](https://arxiv.org/abs/2010.01412)). The trained RAF-DB model is available in DDAMFN++/checkpoints_ver2.0, which is not our best. The affectnet model will soon be available.

**Comment by simon20010923** [comment]
Our new version DDAMFN++ is available in the folder https://github.com/simon20010923/DDAMFN/tree/main/DDAMFN%2B%2B, which includes new alignment code refer to https://github.com/biubug6/Pytorch_Retinaface and optimized by SAM ([Sharpness aware minimization for efficiently improving generalization](https://arxiv.org/abs/2010.01412)). The trained RAF-DB model is available in DDAMFN++/checkpoints_ver2.0, which is not our best. The affectnet model will soon be available.
