### ISSUE TITLE
About pretrained model

### ISSUE THREAD

**Issue by study-clever** [simon20010923/DDAMFN#3]
Thank you very much for your work! May I ask how you pre-trained the MFN backbone on the Ms-Celeb-1M dataset? How should I pre-train my own backbone model using the Ms-Celeb-1M dataset? Please forgive my foolish question.

**Comment by simon20010923** [comment]
Thank you for your interest in our project. I'm on a business trip now. I will pose the pretrain model after 01/01/2024. I will cue you when it's available.

**Comment by simon20010923** [comment]
The code is updated and the pretrained model is available.

**Comment by study-clever** [comment]
> 代码已更新，预训练模型可用。

Thank you very much

**Comment by simon20010923** [comment]
Our new version DDAMFN++ is available in the folder https://github.com/simon20010923/DDAMFN/DDAMFN++, which includes new alignment code refer to https://github.com/biubug6/Pytorch_Retinaface and optimized by SAM ([Sharpness aware minimization for efficiently improving generalization](https://arxiv.org/abs/2010.01412)). The trained RAF-DB model is available in DDAMFN++/checkpoints_ver2.0, which is not our best. The affectnet model will soon be available.

**Comment by simon20010923** [comment]
Our new version DDAMFN++ is available in the folder https://github.com/simon20010923/DDAMFN/tree/main/DDAMFN%2B%2B, which includes new alignment code refer to https://github.com/biubug6/Pytorch_Retinaface and optimized by SAM ([Sharpness aware minimization for efficiently improving generalization](https://arxiv.org/abs/2010.01412)). The trained RAF-DB model is available in DDAMFN++/checkpoints_ver2.0, which is not our best. The affectnet model will soon be available.
