### ISSUE TITLE
FERPlus checkpoint

### ISSUE THREAD

**Issue by dpigasin** [simon20010923/DDAMFN#4]
Hello, could you please provide a checkpoint for the model trained on FERPlus?

**Comment by dpigasin** [comment]
And data preparation scripts

**Comment by simon20010923** [comment]
Sir, maybe you can train your own model now since I'm not available to get the model these days. And for data preparation, we put images into folders with different numbers for different expressions. I think you may check how others do. We did the same.

**Comment by simon20010923** [comment]
Our new version DDAMFN++ is available in the folder https://github.com/simon20010923/DDAMFN/DDAMFN++, which includes new alignment code refer to https://github.com/biubug6/Pytorch_Retinaface and optimized by SAM ([Sharpness aware minimization for efficiently improving generalization](https://arxiv.org/abs/2010.01412)). The trained RAF-DB model is available in DDAMFN++/checkpoints_ver2.0, which is not our best. The affectnet model will soon be available.

**Comment by simon20010923** [comment]
Our new version DDAMFN++ is available in the folder https://github.com/simon20010923/DDAMFN/tree/main/DDAMFN%2B%2B, which includes new alignment code refer to https://github.com/biubug6/Pytorch_Retinaface and optimized by SAM ([Sharpness aware minimization for efficiently improving generalization](https://arxiv.org/abs/2010.01412)). The trained RAF-DB model is available in DDAMFN++/checkpoints_ver2.0, which is not our best. The affectnet model will soon be available.
