### ISSUE TITLE
FERPlus Preprocessing

### ISSUE THREAD

**Issue by ArnabKumarRoy02** [simon20010923/DDAMFN#6]
The paper mentioned that you guys have used `RetinaFace` for detecting faces and landmark as part of your preprocessing. And as per the paper says, `27,298` images were used in training for FERPlus. 

I tried to implement the same and got around `7000` training images, most of them saying that it couldn't detect any faces. 

How did you guys manage to detect so many samples? If possible update the changes in the code.

**Comment by simon20010923** [comment]
Please set the parameters of retinaface and resize the image to the size corresponding to the best performance of the model. Retinaface can detect almost all faces in the face images in the ferplus data set.

**Comment by ArnabKumarRoy02** [comment]
Can you please mention which `retinaface` library, as there are many libraries with such name.

I used this one: [RetinaFace](https://pypi.org/project/retina-face/)
Also changing the parameters, threshold (let's say) was set to 0.2 (just for checking with image size of 400 x 400), still a lot of faces in the images were not being detected.

**Comment by simon20010923** [comment]
Test the parameters. One will work.

**Comment by simon20010923** [comment]
Our new version DDAMFN++ is available in the folder https://github.com/simon20010923/DDAMFN/DDAMFN++, which includes new alignment code refer to https://github.com/biubug6/Pytorch_Retinaface and optimized by SAM ([Sharpness aware minimization for efficiently improving generalization](https://arxiv.org/abs/2010.01412)). The trained RAF-DB model is available in DDAMFN++/checkpoints_ver2.0, which is not our best. The affectnet model will soon be available.

**Comment by simon20010923** [comment]
Our new version DDAMFN++ is available in the folder https://github.com/simon20010923/DDAMFN/tree/main/DDAMFN%2B%2B, which includes new alignment code refer to https://github.com/biubug6/Pytorch_Retinaface and optimized by SAM ([Sharpness aware minimization for efficiently improving generalization](https://arxiv.org/abs/2010.01412)). The trained RAF-DB model is available in DDAMFN++/checkpoints_ver2.0, which is not our best. The affectnet model will soon be available.
